export XDG_CONFIG_HOME="$HOME/.config/"
export XDG_CACHE_HOME="$HOME/.cache/"



export EDITOR='nvim'
export TERMINAL='alacritty'
export BROWSER='firefox'

#--------------------------------------------
# Alias
#--------------------------------------------

alias ls="ls --color -F"


#--------------------------------------------
# Autocompletion
#--------------------------------------------

autoload -Uz compinit
zstyle ':completion:*' menu select


#--------------------------------------------
# Them
#--------------------------------------------

autoload -Uz promptinit && promptinit

# Define costum theme
prompt_frozentheme_setup() {
  PS1="%~%# "
}

# Add the theme to promptsys
prompt_themes+=( frozentheme )

# Load the theme
prompt default
