#!/bin/bash

COUNTER=0
for f in ~/.dotfiles/.config/* 
do
  if [[ -d $f ]]; then
    CONFIG_NAME=${f##*/.config/}
     if [[ -d ~/.config/"$CONFIG_NAME" ]]
     then 
       echo "'$CONFIG_NAME': config exist"
     else 
       ln -s "$f" ~/.config/
       (( COUNTER++))
       echo "$CONFIG_NAME: linked"
     fi
  fi
done
echo "'$COUNTER configs new linked'"

