#--------------------------------------------
# ENV
#--------------------------------------------

[env]
WINIT_X11_SCALE_FACTOR = "1.0"
opacity = "0.8"
decorations  = "Buttonless"


#--------------------------------------------
# window
#--------------------------------------------

[window]
decorations = "Full"
dynamic_padding = true 
dynamic_title = true


[window.padding]
x = 0
y = 0

[window.dimensions]
columns = 120
lines = 85


#--------------------------------------------
# font
#--------------------------------------------
[font]
size=12


#--------------------------------------------
# cursor
#--------------------------------------------

[cursor.style]
shape = "Underline"
blinking="Never"
#vi_mode_style = {,""}


#--------------------------------------------
# mouse
#--------------------------------------------

[mouse]
hide_when_typing = true 


#--------------------------------------------
# keyboard
#--------------------------------------------

[keyboard]
bindings = [
  {key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]


#--------------------------------------------
# hints
#--------------------------------------------

[[hints.enabled]]
regex = "[^ ]+\\.rs=\\d+:\\d+"
command = {program = "editor", args = [ "--goto" ] }
mouse = {enabled = true}
  

#--------------------------------------------
# colors
# color theme "challenger_deep" 
#--------------------------------------------

# Default colors
[colors.primary]
background= '0x1b182c'
foreground= '0xcbe3e7'

# Normal colors
[colors.normal]
black=   '0x100e23'
red=     '0xff8080'
green=   '0x95ffa4'
yellow=  '0xffe9aa'
blue=    '0x91ddff'
magenta= '0xc991e1'
cyan=    '0xaaffe4'
white=   '0xcbe3e7'

# Bright colors
[colors.bright]
black=   '0x565575'
red=     '0xff5458'
green=   '0x62d196'
yellow=  '0xffb378'
blue=    '0x65b2ff'
magenta= '0x906cff'
cyan=    '0x63f2f1'
white=   '0xa6b3cc'
